name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  python-bindings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: version info
        run:  rustc --version; cargo --version;

      - name: Install python headers
        run: sudo apt-get update && sudo apt-get install python3-dev python3-pip python3-venv

      - name: Install maturin
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip3 install toml
          pip3 install maturin
          pip3 show maturin
      - name: add library to venv
        run: |
          . venv/bin/activate
          cd lib
          maturin develop --features=python
      - name: compile finch with python bindings
        run: |
          . venv/bin/activate
          cd lib
          maturin build --features=python --release --strip --manylinux=off

  tests:
    strategy:
      matrix:
        rust-version: [stable]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}
          override: true

      - name: version info
        run:  rustc --version; cargo --version;

      - name: Run all tests
        run: cargo test --all

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings
